const {chromium}=require('playwright');
const assert=(x,m)=>{if(!x)throw new Error(m)};
const URL='http://127.0.0.1:4331/index.html';
async function context(browser,w=390,h=844){const c=await browser.newContext({viewport:{width:w,height:h},serviceWorkers:'block'});const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.addInitScript(()=>{localStorage.setItem('fuwaLocalModeV1','1');localStorage.setItem('fuwaTutorialSeenV1','1');localStorage.setItem('fuwaFeatureTutorial:v1:me','1');window.alert=()=>{};window.confirm=()=>true;});await p.goto(URL,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.fuwaSmartApi&&window.fuwaSmartDebug);return{c,p,errors}}
async function seed(p){await p.evaluate(async()=>{const open=indexedDB.open('FuwaDB',13);const db=await new Promise((res,rej)=>{open.onsuccess=()=>res(open.result);open.onerror=()=>rej(open.error)});const tx=db.transaction(['entries','tinyJoys','moodCheckins','dailyCheckins'],'readwrite'),now=Date.now();[
{id:'smart-work-1',date:'2026-08-15',mood:'low',title:'Office pressure',body:'The deadline and meeting pressure at the office felt heavy today.',tags:['work'],threadIds:[],createdAt:now-1000,updatedAt:now-1000},
{id:'smart-japan',date:'2026-07-02',mood:'amazing',title:'Tokyo evening',body:'Walking around Tokyo after dinner made me happy and calm. Japan felt bright.',tags:['travel'],threadIds:[],createdAt:now-40*86400000,updatedAt:now-40*86400000},
{id:'smart-work-old',date:'2026-06-01',mood:'okay',title:'Work boundary',body:'I noticed that office meetings are easier when I leave the deadline pressure at work.',tags:['work'],threadIds:[],createdAt:now-75*86400000,updatedAt:now-75*86400000},
{id:'smart-friend-1',date:'2026-08-10',mood:'good',title:'Coffee',body:'Had coffee with Mika at Shibuya and laughed for a long time.',tags:[],threadIds:[],createdAt:now-5*86400000,updatedAt:now-5*86400000},
{id:'smart-friend-2',date:'2026-08-11',mood:'good',title:'Call',body:'Talked to Mika again after work. It was comforting.',tags:[],threadIds:[],createdAt:now-4*86400000,updatedAt:now-4*86400000}
].forEach(x=>tx.objectStore('entries').put(x));tx.objectStore('tinyJoys').put({id:'joy-1',date:'2026-08-14',text:'A quiet dinner made me smile',createdAt:now-86400000,updatedAt:now-86400000});for(let i=0;i<6;i++){const d=new Date(now-(i+1)*86400000).toISOString().slice(0,10);tx.objectStore('moodCheckins').put({id:'m'+i,date:d,mood:i<3?'good':'sad',createdAt:now-i});tx.objectStore('dailyCheckins').put({id:'d'+i,date:d,sleepHours:i<3?8:5,energy:i<3?4:2,rating:i<3?4:2,createdAt:now-i});}await new Promise((res,rej)=>{tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close();});}
(async()=>{const b=await chromium.launch({headless:true});
  {const{c,p,errors}=await context(b);await seed(p);await p.reload({waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.fuwaSmartDebug);const r=await p.evaluate(()=>({search:window.fuwaSmartDebug.searchDocs('overwhelmed at work',{limit:6}).map(x=>x.id),ask:window.fuwaSmartDebug.askFuwa('When did I last mention Japan?'),weekly:window.fuwaSmartDebug.weeklyStory(),patterns:window.fuwaSmartDebug.moodInsights(),rhythm:window.fuwaSmartDebug.rhythm(),tn:window.fuwaSmartDebug.smartThenNow(),entities:window.fuwaSmartDebug.entityPages()}));assert(r.search.includes('smart-work-1'),'semantic search failed');assert(r.ask.docs.some(x=>x.id==='smart-japan'),'Ask Fuwa failed');assert(!r.weekly.empty,'weekly story failed');assert(r.patterns.length,'mood insight failed');assert(r.rhythm,'rhythm failed');assert(r.tn?.older,'Then & Now failed');assert(r.entities.people.some(x=>x.name==='Mika'),'people page failed');await p.evaluate(()=>window.fuwaSmartApi.navigate('smart'));await p.waitForTimeout(100);assert(await p.locator('#smartView').evaluate(el=>el.classList.contains('active')),'smart view inactive');await p.locator('#fuwaSmartSearch').fill('overwhelmed at work');await p.waitForTimeout(240);assert((await p.locator('#fuwaSmartSearchResults').innerText()).includes('Office pressure'),'smart search UI failed');await p.locator('#fuwaAskInput').fill('Show me happy memories');await p.locator('#fuwaAskForm button').click();assert((await p.locator('#fuwaAskAnswer').innerText()).includes('brighter'),'Ask UI failed');await p.evaluate(()=>window.fuwaSmartApi.createThread({title:'Work',description:'QA',emoji:'☁️',entryIds:['smart-work-1','smart-work-old']}));const linked=await p.evaluate(()=>{const s=window.fuwaSmartApi.snapshot().data,t=s.threads.find(x=>x.title==='Work');return!!t&&s.entries.filter(x=>['smart-work-1','smart-work-old'].includes(x.id)).every(x=>x.threadIds.includes(t.id))});assert(linked,'atomic smart thread link failed');await p.evaluate(()=>window.fuwaSmartApi.openEntry('smart-work-1'));await p.waitForTimeout(100);const before=await p.locator('#entryBody').inputValue();await p.locator('[data-write-help="gentle"]').click();assert(await p.locator('#entryBody').inputValue()===before,'writing helper mutated before approval');await p.locator('[data-write-apply]').click();assert((await p.locator('#entryBody').inputValue()).length>before.length,'approved writing help not applied');assert(!errors.length,errors.join('|'));await c.close();}
  {const{c,p}=await context(b);await p.evaluate(async()=>{const open=indexedDB.open('FuwaDB',13),db=await new Promise((res,rej)=>{open.onsuccess=()=>res(open.result);open.onerror=()=>rej(open.error)}),tx=db.transaction('entries','readwrite'),store=tx.objectStore('entries'),now=Date.now();for(let i=0;i<1500;i++)store.put({id:'perf-'+i,date:new Date(now-(i%365)*86400000).toISOString().slice(0,10),mood:i%3?'good':'okay',title:'Journal '+i,body:i%11===0?'A stressful office deadline needed quiet rest afterward.':'A small ordinary day with music and dinner.',tags:[],threadIds:[],createdAt:now-i*1000,updatedAt:now-i*1000});await new Promise((res,rej)=>{tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close()});await p.reload({waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.fuwaSmartDebug);const perf=await p.evaluate(()=>{window.fuwaSmartDebug.invalidate();const t=performance.now(),idx=window.fuwaSmartDebug.ensureIndex(),build=performance.now()-t,q=performance.now(),res=window.fuwaSmartDebug.searchDocs('office stress',{limit:20});return{build,query:performance.now()-q,docs:idx.docs.length,res:res.length}});assert(perf.docs>=1500,JSON.stringify(perf));assert(perf.build<700,`index slow ${JSON.stringify(perf)}`);assert(perf.query<150,`query slow ${JSON.stringify(perf)}`);assert(perf.res>0,'perf search empty');console.log('performance',perf);await c.close();}
  const sizes=[[320,568],[375,812],[390,844],[430,932],[768,1024],[1024,768],[820,1180],[1180,820],[834,1194],[1194,834],[1024,1366],[1366,1024]];for(const[w,h]of sizes){const{c,p,errors}=await context(b,w,h);await p.evaluate(()=>window.fuwaSmartApi.navigate('smart'));await p.waitForTimeout(70);const g=await p.evaluate(()=>({sw:document.documentElement.scrollWidth,iw:innerWidth,nodes:document.getElementsByTagName('*').length,active:document.getElementById('smartView')?.classList.contains('active')}));assert(!errors.length,`${w}x${h} ${errors.join('|')}`);assert(g.sw<=g.iw+2,`${w}x${h} overflow`);assert(g.nodes<10000,`${w}x${h} DOM runaway`);assert(g.active,`${w}x${h} inactive`);await c.close();}
  {const{c,p}=await context(b);await p.locator('.bottom-nav [data-nav="me"]').click();await p.waitForTimeout(500);assert(await p.locator('#moodCheckinModal').evaluate(el=>el.classList.contains('hidden')),'delayed mood check-in escaped Home');await p.locator('#openSettingsButton').click();await p.evaluate(()=>document.getElementById('cloudBackupCard')?.classList.remove('local-hidden'));await p.locator('#cloudRestoreButton').click();await p.waitForTimeout(80);assert(await p.evaluate(()=>document.body.classList.contains('cloud-restore-open')),'restore isolation missing');const layer=await p.evaluate(()=>({settings:getComputedStyle(document.getElementById('settingsSheet')).pointerEvents,restore:getComputedStyle(document.getElementById('cloudRestoreModal')).pointerEvents,z:Number(getComputedStyle(document.getElementById('cloudRestoreModal')).zIndex)}));assert(layer.settings==='none'&&layer.restore==='auto'&&layer.z>1000000,JSON.stringify(layer));await c.close();}
  await b.close();console.log('Fuwa v97 browser QA passed');
})().catch(e=>{console.error(e);process.exit(1)});